spring.application.name=ecommerce_backend

#server port
server.port = 8081

#database details
spring.datasource.url = jdbc:mysql://localhost:3307/ecommerce_spring

spring.datasource.username = root
spring.datasource.password =

#autocreate tables in database using Models
spring.jpa.hibernate.ddl-auto = update

#show SQL Queries in console
spring.jpa.show-sql = true

#file Upload
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 20MB